### ISSUE TITLE
Add either delete or open in file explorer to the context menu

### ISSUE THREAD

**Issue by jeffvli** [jeffvli/feishin#103]
### Discussed in https://github.com/jeffvli/feishin/discussions/82

<div type='discussions-op-text'>

<sup>Originally posted by **isle9** April 14, 2023</sup>
I'd like to be able to delete songs directly or somewhat directly from feishin.
Delete should ideally delete to the OS trash folder if implemented.

If that's not possible, hopefully we can open the folder where the file is located.</div>

**Comment by isle9** [comment]
Any updates on this feature? Just being able to open the folder would do wonders.

**Comment by kgarner7** [comment]
Opening (or copying, if in the web) is available from the `Get info` modal as of https://github.com/jeffvli/feishin/commit/2c17458fdfbe9312a0bad9535e9ff8377721a0f6. Deleting (unless Jeff decides to implement it) is not planned.
Note that, because there is no guarantee that the path actually exists at the location given (may be Docker, or another host), it will not be added directly to the context menu

**Comment by isle9** [comment]
Hey @kgarner7. I've tested the latest version using Vercel, but I can't neither copy or click on my path.

**Comment by kgarner7** [comment]
![image](https://github.com/jeffvli/feishin/assets/17521368/de16688e-ecc0-49ac-99d8-945951ee110c)
You may need to do a hard ~~reset~~ refresh (control/command + shift + r typically does it) on your browser, but I can confirm it is there

**Comment by isle9** [comment]
Oh, my bad. Seems like I was using the wrong version.

This is still a bit awkward though. Are there any plans on making it into a clickable link instead?

**Comment by kgarner7** [comment]
Given that `file://` urls don't appear to work in web, no (you _can_ click and select on the text, unlike most items)

**Comment by isle9** [comment]
Seems like this one was implemented in the end.
