### ISSUE TITLE
Album cover in the bottom left not square

### ISSUE THREAD

**Issue by evangelear** [jeffvli/feishin#158]
## Expected Behavior

![Снимок экрана 2023-06-23 162750](https://github.com/jeffvli/feishin/assets/133697615/0c13a5a8-8ade-439d-a1de-45e591e4d1b8)

Album cover art in the bottom left should be square.

## Current Behavior

Alas, the album covers are not square.

![Снимок экрана 2023-06-23 162713](https://github.com/jeffvli/feishin/assets/133697615/fc8dbf0e-d056-45c6-bccb-8b09aec01a81)

It seems like they're missing about 10 pixels from the bottom.

- Application version : 0.2.0

**Comment by gelaechter** [comment]
This can be fixed by adding 11 pixels to the [max-height of the sidebar](https://github.com/gelaechter/feishin/blob/121b247e9bdb2a92f3e9abaa65c58c602e4624ff/src/renderer/features/sidebar/components/sidebar.tsx#L62-L63).
I don't know why, since I frankly don't really understand the layout, so @jeffvli should probably have a look at it once he has time.
