### ISSUE TITLE
Add Ability to Clear Song/Image Cache

### ISSUE THREAD

**Issue by CCBMhf** [jeffvli/feishin#182]
Sonixd had the feature of being able to clear and reload the Song/Image cache when things would get stuck in a cached state and not want to update properly. I'm currently having this issue with a few albums, specifically with their track art, and was surprised to see this missing in Feishin.

Any chance this could get added?

**Comment by jeffvli** [comment]
If you're using Navidrome, it's possible that it's an issue with Navidrome's image cache rather than Feishin itself. You can go to your Navidrome appdata folder and delete `/cache/images` and restart your instance to see if it fixes it.

Though in case it's not, then I'll implement this when I have the chance.
