### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by hatiac** [jeffvli/feishin#2]
## Expected Behavior

Feishin should login after entering server URL, username and password choosing "Login".

## Current Behavior

Feishin gives error "Cannot read properties of undefined (reading 'accessToken') when trying to log in to my Subsonic server. This is working normally in Sonixd.

## Steps to Reproduce

1. Subsonic server running behind reverse proxy.

2. Try to login with Feishin

## Environment

- Feishin version: 0.0.1-alpha1
- Client operating system and version : Windows 11, 22H2
- Music server: Subsonic 6.1.6

**Comment by jeffvli** [comment]
Feishin requires its own server and will scan your Subsonic server to populate its database. On the login screen, you'll then enter the server URL for the feishin server as well as the default login credentials of `admin/admin`.

Check the [getting started](https://github.com/jeffvli/feishin#getting-started) section of the readme for how to setup.

**Comment by hatiac** [comment]
Sorry, I have been mistaken here. Somehow thought that it was only for development. Case closed. :)

**Comment by rombat** [comment]
@jeffvli I don't wan't to open another issue since I'm pretty sure I just don't understand how it should work, but I can't login, it just loads endlessly.
The default server URL is feishin URL, not my Navidrome server URL, right ?
and the default credentials are admin/admin, right ?
I've tried that, and it just loads endlessly.
I've also tried with my Navidrome credentials, same result.

**Comment by jeffvli** [comment]
@rombat Yep the current version of Feishin uses two separate containers to launch both the database and the server. You'll need both of those running with docker (compose is optional for ease of setup).

I'm currently switching gears to go back to a serverless setup for Feishin, like Sonixd currently is.
