### ISSUE TITLE
Albums with the same title but different artists are merged together in queue

### ISSUE THREAD

**Issue by ghost** [jeffvli/feishin#287]
## Expected Behavior

The album I press play on will play

## Current Behavior

If I have two albums with the same name but different artists, both will be played if i play one of them in the Albums category.

## Steps to Reproduce

1. Get two albums with the same name (in my case Untitled by Rammstein and Untitled by Korn)

2. Select 'Albums' in the sidebar

3. Press play on one of the albums

## Context

There is no context, I wanted to listen to music.

## Your Environment

feishin version: 0.3.0
Operating System: Gentoo Linux 6.1.41
Server: Jellyfin 10.8.10

**Comment by ergonomic-paragraph** [comment]
I'm also experiencing this on v0.5.1 (Windows 10 22H2 and macOS 13.6.1)

**Comment by Diagon** [comment]
The same happens if the same artist has 2+ releases with the same name (e.g. [here](https://musicbrainz.org/release-group/902331d8-67aa-3b3c-bb2a-786d6a66c823) & [here](https://musicbrainz.org/release-group/b1f3d25e-80ba-47f6-b0b8-7310e0dfe3e2))
![Screenshot_20231204_161041](https://github.com/jeffvli/feishin/assets/4415163/df9b253c-57bc-4ff6-b2ab-9bb5ad764ba2)

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/19a88fea86817d8bb40d4a9f47868e1422a00abb, but this is ultimately a Jellyfin bug. See https://github.com/jellyfin/jellyfin/blob/c566ccb63bf61f9c36743ddb2108a57c65a2519b/Emby.Server.Implementations/Data/SqliteItemRepository.cs#L3622-L3625 for why
