### ISSUE TITLE
Create a Windows release

### ISSUE THREAD

**Issue by bacongobbler** [jeffvli/feishin#34]
Sonixd's release page contains Windows builds. I'd love the ability to download the latest release of feishin that was windows-compatible.

If it's possible to use linux releases under [WSLg](https://github.com/microsoft/wslg), that's cool too.

**Comment by Chaphasilor** [comment]
There already is a windows release: https://github.com/jeffvli/feishin/releases/download/v0.0.1-alpha5/Feishin-0.0.1-alpha5-win-x64.exe

Because there so many release artifacts, you need to expand the list to see them: 
![image](https://user-images.githubusercontent.com/18015147/222219216-aeeb16f9-84db-4e5e-a10d-0f7a9b90c532.png)
(click on "Show all 18 assets")

**Comment by bacongobbler** [comment]
Oh thanks! I just noticed this. Closing.
