### ISSUE TITLE
Unable to select an Audio Player

### ISSUE THREAD

**Issue by daredoes** [jeffvli/feishin#375]
## Expected Behavior

When navigating to the playback page of the settings, the user is able to select MPV Player instead of Web Player

## Current Behavior

An error message appears saying unable to load the audio devices

<img width="349" alt="image" src="https://github.com/jeffvli/feishin/assets/6538753/69c41da4-b6d4-4c8e-91d7-09a377794134">

## Steps to Reproduce

1. Run the docker image on a NAS server like a Synology using Portainer
2. Install MPV manually using `apk add` in a docker shell
3. Go to the playback page for a server
4. Error Message

## Possible Solution (Not obligatory)
Add more documentation to configure this before the server first starts via a config file.

## Context

I am trying to use Feishin to act as a JukeBox webpage where any user can trigger playback on it, and have the MPV Player control audio for the server which has the audio from mpv piped to Snapcast

## Your Environment
-   Application version (e.g. v0.1.0) : 0.5.1
-   Operating System and version (e.g. Windows 10) : Docker/Linux
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome

**Comment by kgarner7** [comment]
A couple of things:
1. What browser are you using? This error message is happening because `navigator.mediaDevices.enumerateDevices()` is failing (this could be a bug, or a browser issue)
2. Installing MPV in the Feishin container won't do anything. This is only possible on the desktop app; the DOcker image just serves a webpage (your web browser has no way to communicate with MPV).
3. If you want a jukebox, I might recommend using the develop instance of Navidrome and using the Jukebox feature (a subsonic API feature).

**Comment by gabhab** [comment]
> 3. If you want a jukebox, I might recommend using the develop instance of Navidrome and using the Jukebox feature (a subsonic API feature).

Probably a very stupid question, but: I just installed Feishin, and it seems great, but how do I actually control the Jukebox mode in Navidrome (which is now in the main branch) in Feishin?

**Comment by kgarner7** [comment]
You need a client that actually supports jukebox controls (which is currently not Feishin).

**Comment by gabhab** [comment]
Ah, thanks! I misread point 3 as saying that Feishin supported jukebox. Thanks for clarifying. I hope it does at some point - it seems great otherwise.

**Comment by kgarner7** [comment]
On desktop, this should be resolved by https://github.com/jeffvli/feishin/commit/af69a584183c2a08be1222bc7418fb898b8ac60a.
