### ISSUE TITLE
Album Artist displayed for all tracks in Album view

### ISSUE THREAD

**Issue by ssnarf** [jeffvli/feishin#51]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Tracks in Album view table should show track artists.

## Current Behavior

Album artist is shown for each track.

## Steps to Reproduce

1. Browse any album where the track artist differs from the album artist (i.e. compilations).

## Possible Solution (Not obligatory)

The `artists` property of `ALBUM_CARD_ROWS` appears to duplicate the route of `albumArtists` therefore returning the album artist in all rows.

https://github.com/jeffvli/feishin/blob/55e2a9bf371ee6ee9302357d579ee21969c5e566/src/renderer/components/card/card-rows.tsx#L133-L149

## Context
There's absolutely no expectation that you should jump on this 😄 
I'll look at what I need to do to build the app myself and see if I can create a working PR.

## Your Environment

Windows 10. Jellyfin server.

**Comment by jeffvli** [comment]
Can you clarify what you mean by Album view table? 

Is this the:
1. Track list inside the album detail page?
2. Or are you talking about the album list?

I'm wondering since the `ALBUM_CARD_ROWS` only applies to the `Card` and `Poster` views on the album list, but your additional context leads me to believe you might be talking about the album detail page.

---

If you're talking about the album detail page, I'm seeing compilation albums list artists properly per track.

![image](https://user-images.githubusercontent.com/42182408/224784123-a8e95827-1016-439a-8541-b7da8e09c00c.png)

It's being set in the `combined-title-cell`.

https://github.com/jeffvli/feishin/blob/ef4cdfa0281241aece6c0f54b53fcb3a7515428a/src/renderer/components/virtual-table/cells/combined-title-cell.tsx#LL48-L52C15

**Comment by ssnarf** [comment]
First off, sorry - I though I had added a screenshot. You're right, I am talking about the track list inside the album detail page.

![albumdetail](https://user-images.githubusercontent.com/22354089/224927203-ccaf6848-3d79-480c-9511-96b3bc5d4c02.png)

Viewing the same in Jellyfin web displays the expected artist names.

![jf_albumdetail](https://user-images.githubusercontent.com/22354089/224927880-7248c8fe-b52b-4b1c-94b0-d40c4df83af8.png)

Looking at your screenshot, I think the difference might be media tag related. For my album, the albumartist tag is set to "Various Artists". I think perhaps this tag is not set in your album.

When I remove this tag from my album, artist names are displayed as expected. Then in the album heading is a list of the track artists where the album artist was previously.

![albumdetail_2](https://user-images.githubusercontent.com/22354089/224930861-10c25e3c-3893-4d5b-8b3e-b10a39e79324.png)

For Various Artists albums, this isn't an issue. However I have a lot of DJ mixes where the DJ name is used as the album artist so keeping this tag intact would be preferable.

For reference, here is how a tag looked before I removed the albumartist.
```
Input #0, mp3, from '1-01 Kenny Loggins - Footloose.mp3':
  Metadata:
    title           : Footloose
    artist          : Kenny Loggins
    track           : 1/21
    album           : The Best ’80s Car Songs Album in the World… Ever!
    disc            : 1/3
    genre           : Pop
    compilation     : 1
    TMED            : CD
    SCRIPT          : Latn
    publisher       : Spectrum Music
    artist-sort     : Loggins, Kenny
    album_artist    : Various Artists
    TSO2            : Various Artists
    ASIN            : B08PJD15N7
    originalyear    : 2021
    BARCODE         : 600753934968
    ARTISTS         : Kenny Loggins
    MusicBrainz Album Status: official
    MusicBrainz Album Release Country: GB
    MusicBrainz Album Type: album/compilation
    MusicBrainz Album Id: 34bef51b-3546-4c20-896e-913bef11ecb3
    MusicBrainz Artist Id: 15042d2b-2d4c-4451-a96a-6f547642de13
    MusicBrainz Album Artist Id: 89ad4ac3-39f7-470e-963a-56509c546377
    MusicBrainz Release Group Id: 806d26a1-68f1-465b-8f6d-8e0c40c1077e
    MusicBrainz Release Track Id: 8019fbff-f943-4605-9f21-55637e992873
    TORY            : 2021
    date            : 2021-02-05
```

**Comment by jeffvli** [comment]
Ah you're right. My example album isn't tagged correctly.

I did manage to pinpoint the issue though:

https://github.com/jeffvli/feishin/blob/ef4cdfa0281241aece6c0f54b53fcb3a7515428a/src/renderer/components/virtual-table/index.tsx#L267

The `type` should be set by `params.data?.serverType` instead of what it is currently.
Feel free to send in a PR with the change since you deserve credit for spotting this issue!
