### ISSUE TITLE
bug most played songs on homepage 

### ISSUE THREAD

**Issue by apierre55000** [jeffvli/feishin#520]
on the home page, there is most played songs section
but when i clic to the image of album (not the play icon), it show the album but at the top but not the songs 
it shows all my libraries of my jellyfin server as the songs of the album

**Comment by bfg100k** [comment]
I'm facing the same issue as well. I'm guessing its because "Most Played" is showing a song (not an album) and clicking through the interface is for an album not a song? Here's a screenshot - noted that "I GOT YOU" is a song from the album "With You-th" by TWICE

![image](https://github.com/jeffvli/feishin/assets/2188087/5b0b5410-6ba3-451d-940d-20e20c488706)

**Comment by iiPythonx** [comment]
This has been a known issue in the discord server since at least november. Jeffvli had plans to fix it although I'm not actually sure if he did or not yet (on the development branch).

**Comment by kgarner7** [comment]
This is resolved in development by https://github.com/jeffvli/feishin/issues/434 (try it out on https://feishin.vercel.app).
