### ISSUE TITLE
Global hotkeys still not working on 6.1

### ISSUE THREAD

**Issue by auyylaso** [jeffvli/feishin#546]
## Expected Behavior

Pressing hotkey when in other apps should trigger the function
## Current Behavior
Nothing occurs unless the app is currently focused

## Steps to Reproduce
Enable global hot keys attempt to use.

## Context

Just trying to pause music and change songs when playing games without having to tab out of the game
## Your Environment

-   Application version (e.g. v0.1.0) : 6.1
-   Operating System and version (e.g. Windows 10) : Windows 10
-   Server and version (e.g. Navidrome v0.48.0) : JellyFin 10.8.13 Mate Ubuntu 20.04
Linux USERNAME 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by iiPythonx** [comment]
Not able to replicate this on Linux or Windows 10, from my testing it works with both mpv and web players just fine.  
Are you referring to global media keys as in the media keys/function on your keyboard or *custom* global media keys as set in the settings?

**Comment by nathan-contino** [comment]
I'm also experiencing this issue on macOS when I enable global media hotkeys. I see the following popup when I enable the option:

<img width="374" alt="Screenshot 2024-03-16 at 12 21 11" src="https://github.com/jeffvli/feishin/assets/10657588/1eae6b44-02eb-4459-ae55-49df4a4d2cae">

...despite the fact that in **System Settings > Privacy & Security > Accessibility**, I've already enabled (and toggled back and forth, just to be sure) Feishin as a trusted accessibility client.

**Comment by auyylaso** [comment]
> Not able to replicate this on Linux or Windows 10, from my testing it works with both mpv and web players just fine. Are you referring to global media keys as in the media keys/function on your keyboard or _custom_ global media keys as set in the settings?

![image](https://github.com/jeffvli/feishin/assets/70453553/7e9510e3-46fc-490c-aa8d-00b049efed3a)
![image](https://github.com/jeffvli/feishin/assets/70453553/3429817d-8a2e-4595-b3fd-6b2cc9a51651)
This is the hotkeys that aren't functioning. Shift+PageUp Shift+PageDown Shift+End none of them work. Rebooted my pc reinstalled Feishin the global hotkeys have never worked even from 5.3

**Comment by iiPythonx** [comment]
Indeed it would seem that those don't work, not sure why considering the media keys function properly.

**Comment by iiPythonx** [comment]
Actually, nevermind, they do seem to work after setting one as Shift+PageUp, marking it as a global hotkey, and then restarting Feishin. Based on your screenshot, the global media tickbox isn't checked.

**Comment by auyylaso** [comment]
> Actually, nevermind, they do seem to work after setting one as Shift+PageUp, marking it as a global hotkey, and then restarting Feishin. Based on your screenshot, the global media tickbox isn't checked.

I thought the toggle switch was the checkbox lol I feel incredibly dumb as yes when I click the tiny check box that I didn't even notice the last like 6 months I've been using Feishin that resolves the issue.

**Comment by iiPythonx** [comment]
As for this issue:
> I'm also experiencing this issue on macOS when I enable global media hotkeys.

That might be something @kgarner7 knows something about considering they're the one who authored https://github.com/jeffvli/feishin/pull/512.

**Comment by nathan-contino** [comment]
<img width="827" alt="Screenshot 2024-03-22 at 08 59 31" src="https://github.com/jeffvli/feishin/assets/10657588/bf37f57d-873f-4631-8327-e8d7671ac4b2">

For any other macOS users struggling with getting the play/pause/skip/prev keys to work on your keyboard, I solved the issue by explicitly granting Feishin the "Media and Apple Music" permission in System Settings > Privacy & Security. I guess Apple's description of "Apple Music, your music and video activity, and your media library" is missing an extra permission this grants -- the global media keys!

@kgarner7 I'm sure this isn't the highest priority issue, but it might be nice to update the error message to explicitly call out the "Media and Apple Music" permission. I tested several other possible permissions, including Full Disk Access (essentially a superpermission that grants everything), but this was the only one that worked.

It's also possible that my setup broke since I upgraded from an earlier version of Feishin, and new users will wind up granting the proper permission through a system dialog when they toggle "global media keys" on. Unfortunately in my case, toggling it off and on again didn't bring up the dialog.

**Comment by anthonymag** [comment]
This still isn't working for me. I uninstalled and reinstalled on Sonoma 14.4.1, I set the "Media & Apple Music" permission, I set the Accessibility permission, and turned on the "global media hotkeys"

Fast forward and rewind still do nothing, and play still opens Apple Music.
I'm on Feishin 0.9.0.

What else might I be missing?
