### ISSUE TITLE
when loading a song from the tracks section the queue loads all the songs lags with a large amount of songs

### ISSUE THREAD

**Issue by Fwuk** [jeffvli/feishin#617]
### Expected Behavior

i would have expected expected a limit on the queue instead of it loading all 20 thousand of my songs to the queue

### Current Behavior

every song gets loaded into the queue

### Steps to Reproduce

have a large amount of music and play a song from the tracks section

### Possible Solution

add a limit the queue preferably adjustable and a docker environment variable for the queue limit for when other people use the web app

### Context

loading songs still happens it just takes a while its fairly annoying. since i intend to continue adding songs to my library the problem is only going to get worse

### Application version

0.7.1

### Operating System and version

webapp, desktop app

### Server and Version

jellyfin

**Comment by kgarner7** [comment]
Closed by https://github.com/jeffvli/feishin/commit/88741a86168bb6ff40ca1c3462822b1679614b13. Adds a new option to configure double click behavior specifically for track search.

Note that double click behavior is otherwise preserved (queue all tracks matching the area). So if you have a very large playlist and double click, it will be expected to queue all tracks. This is expected behavior.
