### ISSUE TITLE
[Request] Show all artists within the artist field instead of only the first one, and sort/display them properly

### ISSUE THREAD

**Issue by Rycia** [jeffvli/feishin#66]
Separating from #9.

I would suggest, if a song has multiple artists; to show all the different artists and scroll them like Spotify does. Both Sonixd and Feishin only show the first artists/album artists; eg `Artist 1` only, even if there's multiple artists.

![image](https://user-images.githubusercontent.com/43384589/228311188-c4cc4606-231d-46bc-99cb-93b36f249d21.png)
![image](https://user-images.githubusercontent.com/43384589/228311396-a9002424-fff0-473d-9397-48ff53a2f149.png)

instead of displaing `Artist 1, Artist 2, Artist 3`

A good idea would also be to concatenate the artist names with the last one having "And" instead of just a separator,
eg. `Artist 1, Artist 2, and Artist 3` and if a artist is marked as a featured artist type, then have it be `Artist 1, Artist 2, featuring Artist 3` and if more than one artist is featured, have it be `Artist 1, featuring Artist 2 and Artist 3` or `Artist 1, ft. Artist 2 and Artist 3` and  `Artist 1, Artist 2, ft. Artist 3` 

It could be extremely useful when determining variants of a song or searching for songs.

Like spotify, when a song name is super long, or artist field is super long, it can cut off or interfere with other text and UI elements, especially with multiple artists showing in the field. Spotify fixes this by making the text for these fields cut off, but it scrolls through horizontally everything within that field so it would never matter how long it is.

This would be a good implementation if you allow viewing multiple artists within a song's name.

I would also suggest, when displaying them, taking the artist tags and sorting them alphabetically with album artist taking priority, and removing duplicate artists in the same tag. This might be a performance hit, so maybe set it up as a setting the user can toggle.

**Comment by isle9** [comment]
This probably depends on the providers, right?
I know that multiple artists should be implemented in Navidrome soon, so maybe then this would be easier to implement.

**Comment by kgarner7** [comment]
1. Show all artists is available in Jellyfin. Navidrome does not support multiple artists/albumartists for a track (follow https://github.com/navidrome/navidrome/pull/2709 if relevant to you).
2. For Jellyfin, the order (at least for well-tagged ones) is the order of the tags themselves. This order is often intentional, so they should not be sorted alphabetically.
3. I'm not too fond of the scroll, but I do agree that _some_ way to expand the artists is good. Unfortunately I don't really have an alternative at this time and there are some current limitations that would make adding links in the item modal difficult

**Comment by kgarner7** [comment]
With the ability for info modal to show (and link) to all artist/album artists, etc. I will mark 3 as resolved as well
