### ISSUE TITLE
Draft - Feishin keeps playing and pausing the song repeatably

### ISSUE THREAD

**Issue by isle9** [jeffvli/feishin#78]
## Expected Behavior

I expected this not to happen under normal circumstances. 

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Application version : 0.0.1-alpha6
- Operating System and version : Ubuntu 22.10
- Node version (if developing locally) :

**Comment by jeffvli** [comment]
Do you have any extra parameters defined in the mpv settings?

I made some changes in the way mpv starts up in the last release.

**Comment by isle9** [comment]
This used to happen even before the latest release and no, I don't have any extra parameters.

**Comment by jeffvli** [comment]
I have not personally encountered this error so can you provide additional context on exactly how the error is occurring?

For example:
1. How the error occurs (with reproduction steps)
2. What media server and version
3. If you have transcoding enabled on your server
4. If this only happens on certain media files (ALAC / FLAC / etc.)
5. A video of the error happening
6. Version of MPV application (or if you are using web player)

**Comment by isle9** [comment]
I'm not really sure when and why it happens, so it's a bit hard to add reproductions steps. It just happens sometimes. I'll try and record a video the next time it happens.
I'm using [Navidrome 0.49.3](https://github.com/navidrome/navidrome/releases/tag/v0.49.3) with no transcoding.
All my files are mp3 128 currently.
I'm using mpv 0.34.1 which is more than a year old though, so I'll try and install the newer version first.

**Comment by GustavBrostrom** [comment]
I'm having the same problems:
- Ubuntu 22.10 + KDE Plasma (X11)
- MPV 0.34.1
- Navidrome 0.48.0
- FLAC Playback
- No Transcoding

The problem occurs randomly upon manually starting a new track (only noticed it occurring on manual track-change during playback/starting fresh playback)
This can happen both on a fresh start of Feishin, and after a couple of hours of playback.

I caught a couple of stack-traces (via journald) at the moment I started playback when exhibiting the problem (ip and username replaced):
> Apr 12 10:35:01  plasmashell[2191441]: {
Apr 12 10:35:01  plasmashell[2191441]:   errcode: 5,
Apr 12 10:35:01  plasmashell[2191441]:   verbose: 'Timeout',
Apr 12 10:35:01  plasmashell[2191441]:   method: 'load()',
Apr 12 10:35:01  plasmashell[2191441]:   arguments: [
Apr 12 10:35:01  plasmashell[2191441]:     'http://<ip_address>:4533/rest/stream.view?id=30cacb33a889a04f4aa69490a964a68f&v=1.13.0&c=feishin_&u=<user_name>&s=a7ced9&t=759c0e7b717bcfab89533a86fc32717b'
Apr 12 10:35:01  plasmashell[2191441]:   ],
Apr 12 10:35:01  plasmashell[2191441]:   stackTrace: 'Error: \n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at e.exports.errorMessage (/opt/Feishin-0.0.1-alpha6-linux-x64/resources/app.asar/dist/main/main.js:14:309483)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at Socket.<anonymous> (/opt/Feishin-0.0.1-alpha6-linux-x64/resources/app.asar/dist/main/main.js:14:331475)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at Socket.emit (node:events:513:28)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at addChunk (node:internal/streams/readable:315:12)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at readableAddChunk (node:internal/streams/readable:289:9)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at Socket.Readable.push (node:internal/streams/readable:228:10)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)'
Apr 12 10:35:01  plasmashell[2191441]: }
Apr 12 10:35:01  plasmashell[2191441]: {
Apr 12 10:35:01  plasmashell[2191441]:   errcode: 5,
Apr 12 10:35:01  plasmashell[2191441]:   verbose: 'Timeout',
Apr 12 10:35:01  plasmashell[2191441]:   method: 'load()',
Apr 12 10:35:01  plasmashell[2191441]:   arguments: [
Apr 12 10:35:01  plasmashell[2191441]:     'http://<ip_address>:4533/rest/stream.view?id=30cacb33a889a04f4aa69490a964a68f&v=1.13.0&c=feishin_&u=<user_name>&s=a7ced9&t=759c0e7b717bcfab89533a86fc32717b'
Apr 12 10:35:01  plasmashell[2191441]:   ],
Apr 12 10:35:01  plasmashell[2191441]:   stackTrace: 'Error: \n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at e.exports.errorMessage (/opt/Feishin-0.0.1-alpha6-linux-x64/resources/app.asar/dist/main/main.js:14:309483)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at Socket.<anonymous> (/opt/Feishin-0.0.1-alpha6-linux-x64/resources/app.asar/dist/main/main.js:14:331475)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at Socket.emit (node:events:513:28)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at addChunk (node:internal/streams/readable:315:12)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at readableAddChunk (node:internal/streams/readable:289:9)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at Socket.Readable.push (node:internal/streams/readable:228:10)\n' +
Apr 12 10:35:01  plasmashell[2191441]:     '    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)'
Apr 12 10:35:01  plasmashell[2191441]: }
Apr 12 10:35:02  plasmashell[2191441]: {
Apr 12 10:35:02  plasmashell[2191441]:   errcode: 5,
Apr 12 10:35:02  plasmashell[2191441]:   verbose: 'Timeout',
Apr 12 10:35:02  plasmashell[2191441]:   method: 'load()',
Apr 12 10:35:02  plasmashell[2191441]:   arguments: [
Apr 12 10:35:02  plasmashell[2191441]:     'http://<ip_address>:4533/rest/stream.view?id=30cacb33a889a04f4aa69490a964a68f&v=1.13.0&c=feishin_&u=<user_name>&s=a7ced9&t=759c0e7b717bcfab89533a86fc32717b'
Apr 12 10:35:02  plasmashell[2191441]:   ],
Apr 12 10:35:02  plasmashell[2191441]:   stackTrace: 'Error: \n' +
Apr 12 10:35:02  plasmashell[2191441]:     '    at e.exports.errorMessage (/opt/Feishin-0.0.1-alpha6-linux-x64/resources/app.asar/dist/main/main.js:14:309483)\n' +
Apr 12 10:35:02  plasmashell[2191441]:     '    at Socket.<anonymous> (/opt/Feishin-0.0.1-alpha6-linux-x64/resources/app.asar/dist/main/main.js:14:331475)\n' +
Apr 12 10:35:02  plasmashell[2191441]:     '    at Socket.emit (node:events:513:28)\n' +
Apr 12 10:35:02  plasmashell[2191441]:     '    at addChunk (node:internal/streams/readable:315:12)\n' +
Apr 12 10:35:02  plasmashell[2191441]:     '    at readableAddChunk (node:internal/streams/readable:289:9)\n' +
Apr 12 10:35:02  plasmashell[2191441]:     '    at Socket.Readable.push (node:internal/streams/readable:228:10)\n' +
Apr 12 10:35:02  plasmashell[2191441]:     '    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)'
Apr 12 10:35:02  plasmashell[2191441]: }

As for mpv debug logs, I've only got logs from during "playback", not startup or track initialization, I'll see if I can capture a full log later:
> [  25.046][v][cplayer] Set property: pause=true -> 1
[  25.051][v][cplayer] Set property: pause=false -> 1
[  25.076][v][cplayer] Set property: pause=true -> 1
[  25.078][v][cplayer] Set property: pause=false -> 1
[  25.096][v][cplayer] Set property: pause=true -> 1
[  25.098][v][cplayer] Set property: pause=false -> 1
[  25.115][v][cplayer] Set property: pause=true -> 1
[  25.118][v][cplayer] Set property: pause=false -> 1
[  25.141][v][cplayer] Set property: pause=true -> 1
[  25.146][v][cplayer] Set property: pause=false -> 1

This repeats as long as I let the player keep going.

I cannot pause the track (at least via UI, haven't tried MPRIS hotkeys yet), and if I start a new track the behavior continues with the new track.
The only solution I've found to fix the issue is to restart Feishin.

**Comment by isle9** [comment]
Updating to the latest mpv version seems to have fixed the issue for me.

**Comment by GustavBrostrom** [comment]
I can mention that I haven't had this issue since I made my comment.
So, If neither of us are experiencing this behavior anymore, the issue could probably be closed.

**Comment by jeffvli** [comment]
Thanks for the update. Feel free to re-open if it happens again.

**Comment by iluvatyr** [comment]
Which version of mpv do you use? I am updated to the latest available one in my distribution (mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects) and it still has this issue
