### ISSUE TITLE
Feature requests & feedback

### ISSUE THREAD

**Issue by Rycia** [jeffvli/feishin#9]
Hey, first off, you've done an absolutely amazing job with Feishin! If I knew Typescript _(I'm really looking to learn it at some point)_ I'd contribute to the project myself! I'm in horrible need for a clean and functional music player capable of my grandiose library, and even thought of making one myself. I loved sonixd, so I gave this a try, and it feels a lot better.

I've opened the project on Windows 10 Pro today, and aside from this bug #8, it looks really smooth. 

I found some little design changes I'd suggest to make the app look better. Ignore what you might already be working on.

1:
![image](https://user-images.githubusercontent.com/43384589/213068502-47d5bf71-e6e3-472a-906c-5be81fa7794f.png)
On the playlists tab, there's the two grey buttons and then the up arrow. The up arrow doesn't have a backdrop, but the other 2 do. I believe this would look better if all 3 were consistent without the backdrop and just on top of the black.

2:
![image](https://user-images.githubusercontent.com/43384589/213068692-be364cac-2f7e-4595-ac52-a31587e31ff2.png)
This might only be a thing on Windows 10, but, on any sort of playlist or album UI, I believe the backdrop behind the X, minimize, etc icons on the top right, should be removed. It's unnecessary if the background of the artwork/icon for the album/playlist is darkened a bit, it'll never reach a true white to make the icons invisible. Alternatively, you could pick the color from the backdrop, and if it's too white, turn it black so it's perfectly visible.

3:
![image](https://user-images.githubusercontent.com/43384589/213069215-ae634afe-8f5e-4d4b-a75c-a3da7735d5dc.png)
You should allow the option to only display the year later on. All my tracks are only dated by year, not extended out to month and day, so by default it's showing January 18th.
I would also suggest allowing it to show in the format of `2000, January, 18th` instead of `2000-01-18` ,and omit fields such as the month and day, if they don't exist within the tags. You'd have to allocate `January` to `01` and `1`, but anything out of those bounds, such as `0` , ` `, and `13` default to not showing.

4:
![image](https://user-images.githubusercontent.com/43384589/213070807-6777f1cb-ee52-44dc-952d-b472ab5e7177.png)
![image](https://user-images.githubusercontent.com/43384589/213071095-e5b13ad0-acd4-4bd4-bbdb-4a24953c20db.png)

5:
I also noticed, when clicking on the searchbar, it's in a weird position relative to the close/minimize buttons, and is a bit of a weird size. It would look better if it could be anchored to the right side underneath the X, minimize, ect buttons, probably centered beneath X. Right now it looks a bit freefloaty. And there's plenty of space to do it. Just looks weird to me.
There's also a 2nd searchbar on the left side, so I'm guessing it's being migrated. I would suggest combining the two together and add the option within the search to have `search in: everything`, `search in:this artist` and `search in: this page` dropdowns, etc, defaulting to (as a setting) what the user chooses, that by default being `search in: everything`

6:
Also, weird thing, but when clicking on settings, my antivirus (AVG) was  trying to tell me that Feishen was trying to use my webcam. I'd suggest.. removing that, if that's the case. I'm just letting you know that my antivirus was throwing a fit about it, even if it shouldn't, and that may confuse other people in the future.

7:
I would also suggest packaging MPV with Feishin on windows to both prevent instances where updates of MPV could break Feishin with that specific version. It creates an extra step on Windows users to get another piece of software, and updates can break things both ways if they're not packaged together. Just add a note during the step of selecting it that shows only on Windows that `On Windows, by default, MPV is inside the feishin\mpv folder.` Saves a lot of time programming just for Windows. Not sure how it'd work for other systems.

I'll add more to this later as I find more little issues/suggestions/design changes.

**Comment by jeffvli** [comment]
Just wanted to follow up on this issue (and I know we talked a bit on Discord as well!)

---
### Regarding 1:

I think keeping the background on the buttons makes sense, since they serve a different purpose than the collapse button.

It's been changed in the most recent build to make the playlists separate from the collapsible sidebar sections though so maybe not an issue anymore?

![image](https://user-images.githubusercontent.com/42182408/216903830-9f79ecc0-fbde-4dd5-b2f2-91e11b2f203d.png)

---
### Regarding 2:

Probably a good idea. I'll set it as a transparent background for now, with the possibility to customize it later.

---
### Regarding 3:

Where are you seeing this YYYY-MM-DD value? The list views should have a "Year" column that should show only year instead of the full release date.

---
### Regarding 4 and 5:

I've updated the list pages to add another row for the filters. This should probably help with the search bar not getting too squished when the window width is decreased.

I'm also not sure if I should move the search bar underneath the window controls, since technically those aren't part of the actual page layout. They're positionally fixed to the top right of the window, but will also be removable when the user switches to the macOS style window controls (not implemented yet). I'll test it out to see if it's feasible to fit it under there.

![image](https://user-images.githubusercontent.com/42182408/216906089-f3a8aa4e-5e11-4dc2-9545-8848baba54b7.png)

---
### Regarding 6:

This is probably due to checking for the system audio devices. This allows the user to set a custom audio device to use if they're using the web player. Maybe there's some way to mitigate the AV warning, but otherwise it'll probably stay.

https://github.com/jeffvli/feishin/blob/22fec8f9d3f594a0bd56e24d1ad6cc317a022d92/src/renderer/features/settings/components/playback-tab.tsx#L59-L67

--- 
### Regarding 7: 

TBD

**Comment by Rycia** [comment]
I've waited a bit before coming back here to check on everything. To update;

Regarding 3;
I am seeing this right here in album view among other views. All of these only have a defined year, and is not defined by month or day, so it should only show the year if only defined by year;
and of course these aren't, as of current, correctly shown. Here's some soundtracks I have.
![image](https://user-images.githubusercontent.com/43384589/228302670-3d7fb135-5938-4509-8fe9-f56e681e06a5.png)
I also think that if a album doesn't have a defined date (which these do,) that the dates should be hidden.

Regarding 4 & 5;
I think the way to go would be to not use native controls and build your own, but let the user switch between native and windows/macos built-in controls. One you build yourself will be able to allow you to do whatever you want with it and move it however you like. I just think in some way it should be aligned with the rest of the header.

6; Fair enough. I'm just letting you know, because perhaps there's a way to mitigate it. It's a good project and I'd hate for some unknowing person to be turned away when they're warned about using your webcam even if it doesn't.
My webcam doubles as an audio device in regards for being a microphone. Maybe when defining "look for an audio device," you should specify it as an output, not an input device.



### **I also have a set of some new suggestions.**

For 8;
I already asked on Discord if this was already within the code, and I was told it was, but please make sure that Feishin supports replaygain tags. When using Sonixd for desktop with Navidrome, it seemed to not ever have support to reading replaygain tags. These tags make sure all my tracks are the same value without having to reencode my tracks; which after doing multiple times, will degrade the quality of my tracks. Musicbee does well implementing these tags and it works in musicbee, but Navidrome never read them.

For 9;
You should allow us to set, by default, to automatically filter to favorited/liked/loved songs/albums ect in the Library subtabs. By default, it will show the entire library. Some people (like me) like to play a mix of all my favorites in those tabs the second I open Sonixd, and Feishin.

For 10;
I would suggest, if a song has multiple artists; to show all the different artists and scroll them like Spotify does. Both Sonixd and Feishin only show the first artists/album artists; eg `Artist 1`
![image](https://user-images.githubusercontent.com/43384589/228311188-c4cc4606-231d-46bc-99cb-93b36f249d21.png)
![image](https://user-images.githubusercontent.com/43384589/228311396-a9002424-fff0-473d-9397-48ff53a2f149.png)
instead of `Artist 1, Artist 2, Artist 3`
A good idea would also be to concatenate the artist names with the last one having "And" instead of just a separator, eg.
`Artist 1, Artist 2, and Artist 3` and if a artist is marked as a featured artist type, then have it be `Artist 1, Artist 2, featuring Artist 3` and if more than one artist is featured, have it be `Artist 1, featuring Artist 2 and Artist 3` or `Artist 1, ft. Artist 2 and Artist 3` and  `Artist 1, Artist 2, ft. Artist 3` 
It could be extremely useful when determining variants of a song or searching.

10.5;
I mentioned "scrolling text like spotify," and typically when a song name is super long, or artist field is super long, it can be cut off or interfere with other text and UI elements. Spotify fixes this by making the text for these fields cut off, but it scrolls through horizontally everything within that field so it would never matter how long it is.

I also have 2 things that may be a bug of a sorts, or something not implemented, but I'm not sure, and I'll make another issue(s) on it here; (will edit after it's posted) #61 and #62

**Comment by jeffvli** [comment]
I think there may be a misunderstanding on 3. Are you viewing the albums being sorted by `Recently added`? The third column is actually the date (YYYY-MM-DD) that the album was added to your server, as opposed to the date that the album was released. The third column is dynamic based on what sort is selected on the album list.

For 4/5, I just posted an update over in #22 with dedicated window titlebars. (This can be configured to use the default style without the titlebar).

8 -- I will experiment with adding dedicated toggles / settings for commonly used actions such as audio-exclusive mode and replaygain.

9 -- I'll add a favorites page, since I do agree it's rather annoying to have to use the filters whenever you want to view favorites.

10 and 10.5 -- I'm not a huge fan of the scrolling since it's somewhat distracting if you have the app in the background, but I can probably implement this.

Could you create separate feature requests for each of the above features (8, 9, 10)? It would make it a bit easier for me to track these specific action items and I could close this one. Thanks!

**Comment by Rycia** [comment]
Of course. I'll repost. Feel free to close this if you'd like to. I just didn't want to spam with a bunch of different issues.
See #64 #65 #66

**Comment by jeffvli** [comment]
Closing -- feature requests were split out to separate issues.
