### ISSUE TITLE
Getting "Session expired" at every reboot (navidrome server)

### ISSUE THREAD

**Issue by Aiku1** [jeffvli/feishin#92]
## Expected Behavior

The client should log in automatically.

## Current Behavior

Whenever I reboot my computer (or enough time passes without opening Feishin) I have to manually enter my password again.

## Possible Solution (Not obligatory)

A checkbox to remember the password and automatically recreate the session.

## Your Environment

- Application version : 0.0.10-alpha6
- Operating System and version : Windows 10 22H2

**Comment by jeffvli** [comment]
Still troubleshooting this, it's quite hard since I technically have to wait 24+ hours without touching the login to test. I'm not sure why it's occurring since closing and re-opening the app in shorter term intervals does not trigger the invalidation. It's only after a certain amount of time that the session is being invalidated, but it's not following the set session invalidation that's set in the Navidrome config.

I'm hesitant to add a "remember password" checkbox since that means saving the password in plaintext in the client/browser.

Let's keep discussion centralized in #60 though.
